

/**
 * Represents a geographical location with latitude and longitude coordinates.
 */
export interface Location {
  /**
   * The latitude of the location.
   */
  lat: number;
  /**
   * The longitude of the location.
   */
  lng: number;
}

/**
 * Represents a State and City.
 */
export interface City {
  /**
   * The name of the State.
   */
  state: string;
  /**
   * The name of the City.
   */
  city: string;
}

// Mock Data
const mockStates: string[] = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
  "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
  "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
  "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
  "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
  "New Hampshire", "New Jersey", "New Mexico", "New York",
  "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
  "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
  "West Virginia", "Wisconsin", "Wyoming"
];

const mockCitiesByState: Record<string, City[]> = {
  "Alabama": [
    { state: "Alabama", city: "Auburn" },
    { state: "Alabama", city: "Birmingham" },
    { state: "Alabama", city: "Decatur" },
    { state: "Alabama", city: "Dothan" },
    { state: "Alabama", city: "Hoover" },
    { state: "Alabama", city: "Huntsville" },
    { state: "Alabama", city: "Mobile" },
    { state: "Alabama", city: "Montgomery" },
    { state: "Alabama", city: "Tuscaloosa" },
  ],
  "Alaska": [
    { state: "Alaska", city: "Anchorage" },
    { state: "Alaska", city: "Fairbanks" },
    { state: "Alaska", city: "Juneau" },
    { state: "Alaska", city: "Ketchikan" },
    { state: "Alaska", city: "Sitka" },
  ],
  "Arizona": [
    { state: "Arizona", city: "Chandler" },
    { state: "Arizona", city: "Flagstaff" },
    { state: "Arizona", city: "Gilbert" },
    { state: "Arizona", city: "Glendale" },
    { state: "Arizona", city: "Mesa" },
    { state: "Arizona", city: "Peoria" },
    { state: "Arizona", city: "Phoenix" },
    { state: "Arizona", city: "Scottsdale" },
    { state: "Arizona", city: "Surprise" },
    { state: "Arizona", city: "Tempe" },
    { state: "Arizona", city: "Tucson" },
    { state: "Arizona", city: "Yuma" },
  ],
  "Arkansas": [
    { state: "Arkansas", city: "Conway" },
    { state: "Arkansas", city: "Fayetteville" },
    { state: "Arkansas", city: "Fort Smith" },
    { state: "Arkansas", city: "Hot Springs" },
    { state: "Arkansas", city: "Jonesboro" },
    { state: "Arkansas", city: "Little Rock" },
    { state: "Arkansas", city: "North Little Rock" },
    { state: "Arkansas", city: "Pine Bluff" },
    { state: "Arkansas", city: "Rogers" },
    { state: "Arkansas", city: "Springdale" },
  ],
  "California": [
    { state: "California", city: "Anaheim" },
    { state: "California", city: "Bakersfield" },
    { state: "California", city: "Berkeley" },
    { state: "California", city: "Chula Vista" },
    { state: "California", city: "Concord" },
    { state: "California", city: "Corona" },
    { state: "California", city: "Costa Mesa" },
    { state: "California", city: "Elk Grove" },
    { state: "California", city: "Escondido" },
    { state: "California", city: "Fontana" },
    { state: "California", city: "Fremont" },
    { state: "California", city: "Fresno" },
    { state: "California", city: "Fullerton" },
    { state: "California", city: "Garden Grove" },
    { state: "California", city: "Glendale" },
    { state: "California", city: "Hayward" },
    { state: "California", city: "Huntington Beach" },
    { state: "California", city: "Irvine" },
    { state: "California", city: "Lancaster" },
    { state: "California", city: "Long Beach" },
    { state: "California", city: "Los Angeles" },
    { state: "California", city: "Modesto" },
    { state: "California", city: "Moreno Valley" },
    { state: "California", city: "Murrieta" },
    { state: "California", city: "Napa" },
    { state: "California", city: "Oakland" },
    { state: "California", city: "Oceanside" },
    { state: "California", city: "Ontario" },
    { state: "California", city: "Orange" },
    { state: "California", city: "Oxnard" },
    { state: "California", city: "Palmdale" },
    { state: "California", city: "Pasadena" },
    { state: "California", city: "Pomona" },
    { state: "California", city: "Rancho Cucamonga" },
    { state: "California", city: "Riverside" },
    { state: "California", city: "Roseville" },
    { state: "California", city: "Sacramento" },
    { state: "California", city: "Salinas" },
    { state: "California", city: "San Bernardino" },
    { state: "California", city: "San Diego" },
    { state: "California", city: "San Francisco" },
    { state: "California", city: "San Jose" },
    { state: "California", city: "Santa Ana" },
    { state: "California", city: "Santa Clara" },
    { state: "California", city: "Santa Clarita" },
    { state: "California", city: "Santa Monica" },
    { state: "California", city: "Santa Rosa" },
    { state: "California", city: "Simi Valley" },
    { state: "California", city: "Stockton" },
    { state: "California", city: "Sunnyvale" },
    { state: "California", city: "Temecula" },
    { state: "California", city: "Thousand Oaks" },
    { state: "California", city: "Torrance" },
    { state: "California", city: "Vallejo" },
    { state: "California", city: "Van Nuys" },
    { state: "California", city: "Victorville" },
    { state: "California", city: "Visalia" },
    { state: "California", city: "West Covina" },
  ],
  "Colorado": [
    { state: "Colorado", city: "Arvada" },
    { state: "Colorado", city: "Aurora" },
    { state: "Colorado", city: "Boulder" },
    { state: "Colorado", city: "Centennial" },
    { state: "Colorado", city: "Colorado Springs" },
    { state: "Colorado", city: "Denver" },
    { state: "Colorado", city: "Fort Collins" },
    { state: "Colorado", city: "Grand Junction" },
    { state: "Colorado", city: "Greeley" },
    { state: "Colorado", city: "Lakewood" },
    { state: "Colorado", city: "Longmont" },
    { state: "Colorado", city: "Pueblo" },
    { state: "Colorado", city: "Thornton" },
    { state: "Colorado", city: "Westminster" },
  ],
  "Connecticut": [
    { state: "Connecticut", city: "Bridgeport" },
    { state: "Connecticut", city: "Danbury" },
    { state: "Connecticut", city: "Hartford" },
    { state: "Connecticut", city: "New Britain" },
    { state: "Connecticut", city: "New Haven" },
    { state: "Connecticut", city: "Norwalk" },
    { state: "Connecticut", city: "Stamford" },
    { state: "Connecticut", city: "Waterbury" },
    { state: "Connecticut", city: "West Hartford" },
  ],
  "Delaware": [
    { state: "Delaware", city: "Dover" },
    { state: "Delaware", city: "Middletown" },
    { state: "Delaware", city: "Newark" },
    { state: "Delaware", city: "Smyrna" },
    { state: "Delaware", city: "Wilmington" },
  ],
  "Florida": [
    { state: "Florida", city: "Boca Raton" },
    { state: "Florida", city: "Cape Coral" },
    { state: "Florida", city: "Clearwater" },
    { state: "Florida", city: "Coral Springs" },
    { state: "Florida", city: "Daytona Beach" },
    { state: "Florida", city: "Fort Lauderdale" },
    { state: "Florida", city: "Fort Myers" },
    { state: "Florida", city: "Gainesville" },
    { state: "Florida", city: "Hialeah" },
    { state: "Florida", city: "Hollywood" },
    { state: "Florida", city: "Jacksonville" },
    { state: "Florida", city: "Lakeland" },
    { state: "Florida", city: "Miami" },
    { state: "Florida", city: "Miami Gardens" },
    { state: "Florida", city: "Miramar" },
    { state: "Florida", city: "Orlando" },
    { state: "Florida", city: "Palm Bay" },
    { state: "Florida", city: "Pembroke Pines" },
    { state: "Florida", city: "Pensacola" },
    { state: "Florida", city: "Pompano Beach" },
    { state: "Florida", city: "Port St. Lucie" },
    { state: "Florida", city: "Sarasota" },
    { state: "Florida", city: "St. Petersburg" },
    { state: "Florida", city: "Tallahassee" },
    { state: "Florida", city: "Tampa" },
    { state: "Florida", city: "West Palm Beach" },
  ],
  "Georgia": [
    { state: "Georgia", city: "Albany" },
    { state: "Georgia", city: "Athens" },
    { state: "Georgia", city: "Atlanta" },
    { state: "Georgia", city: "Augusta" },
    { state: "Georgia", city: "Columbus" },
    { state: "Georgia", city: "Johns Creek" },
    { state: "Georgia", city: "Macon" },
    { state: "Georgia", city: "Marietta" },
    { state: "Georgia", city: "Roswell" },
    { state: "Georgia", city: "Sandy Springs" },
    { state: "Georgia", city: "Savannah" },
    { state: "Georgia", city: "South Fulton" },
    { state: "Georgia", city: "Stonecrest" },
    { state: "Georgia", city: "Valdosta" },
    { state: "Georgia", city: "Warner Robins" },
  ],
   "Hawaii": [
    { state: "Hawaii", city: "Ewa Gentry" },
    { state: "Hawaii", city: "Hilo" },
    { state: "Hawaii", city: "Honolulu" },
    { state: "Hawaii", city: "Kailua" },
    { state: "Hawaii", city: "Kaneohe" },
    { state: "Hawaii", city: "Kapolei" },
    { state: "Hawaii", city: "Mililani Town" },
    { state: "Hawaii", city: "Pearl City" },
    { state: "Hawaii", city: "Wahiawa" },
    { state: "Hawaii", city: "Waipahu" },
  ],
  "Idaho": [
    { state: "Idaho", city: "Boise" },
    { state: "Idaho", city: "Caldwell" },
    { state: "Idaho", city: "Coeur d'Alene" },
    { state: "Idaho", city: "Idaho Falls" },
    { state: "Idaho", city: "Meridian" },
    { state: "Idaho", city: "Nampa" },
    { state: "Idaho", city: "Pocatello" },
    { state: "Idaho", city: "Twin Falls" },
  ],
  "Illinois": [
    { state: "Illinois", city: "Arlington Heights" },
    { state: "Illinois", city: "Aurora" },
    { state: "Illinois", city: "Bloomington" },
    { state: "Illinois", city: "Bolingbrook" },
    { state: "Illinois", city: "Champaign" },
    { state: "Illinois", city: "Chicago" },
    { state: "Illinois", city: "Cicero" },
    { state: "Illinois", city: "Decatur" },
    { state: "Illinois", city: "Elgin" },
    { state: "Illinois", city: "Evanston" },
    { state: "Illinois", city: "Joliet" },
    { state: "Illinois", city: "Naperville" },
    { state: "Illinois", city: "Palatine" },
    { state: "Illinois", city: "Peoria" },
    { state: "Illinois", city: "Rockford" },
    { state: "Illinois", city: "Schaumburg" },
    { state: "Illinois", city: "Skokie" },
    { state: "Illinois", city: "Springfield" },
    { state: "Illinois", city: "Waukegan" },
  ],
  "Indiana": [
    { state: "Indiana", city: "Anderson" },
    { state: "Indiana", city: "Bloomington" },
    { state: "Indiana", city: "Carmel" },
    { state: "Indiana", city: "Elkhart" },
    { state: "Indiana", city: "Evansville" },
    { state: "Indiana", city: "Fishers" },
    { state: "Indiana", city: "Fort Wayne" },
    { state: "Indiana", city: "Gary" },
    { state: "Indiana", city: "Hammond" },
    { state: "Indiana", city: "Indianapolis" },
    { state: "Indiana", city: "Lafayette" },
    { state: "Indiana", city: "Muncie" },
    { state: "Indiana", city: "Noblesville" },
    { state: "Indiana", city: "South Bend" },
    { state: "Indiana", city: "Terre Haute" },
  ],
  "Iowa": [
    { state: "Iowa", city: "Ames" },
    { state: "Iowa", city: "Ankeny" },
    { state: "Iowa", city: "Cedar Rapids" },
    { state: "Iowa", city: "Council Bluffs" },
    { state: "Iowa", city: "Davenport" },
    { state: "Iowa", city: "Des Moines" },
    { state: "Iowa", city: "Dubuque" },
    { state: "Iowa", city: "Iowa City" },
    { state: "Iowa", city: "Sioux City" },
    { state: "Iowa", city: "Waterloo" },
    { state: "Iowa", city: "West Des Moines" },
  ],
  "Kansas": [
    { state: "Kansas", city: "Kansas City" },
    { state: "Kansas", city: "Lawrence" },
    { state: "Kansas", city: "Lenexa" },
    { state: "Kansas", city: "Manhattan" },
    { state: "Kansas", city: "Olathe" },
    { state: "Kansas", city: "Overland Park" },
    { state: "Kansas", city: "Salina" },
    { state: "Kansas", city: "Shawnee" },
    { state: "Kansas", city: "Topeka" },
    { state: "Kansas", city: "Wichita" },
  ],
  "Kentucky": [
    { state: "Kentucky", city: "Bowling Green" },
    { state: "Kentucky", city: "Covington" },
    { state: "Kentucky", city: "Elizabethtown" },
    { state: "Kentucky", city: "Florence" },
    { state: "Kentucky", city: "Georgetown" },
    { state: "Kentucky", city: "Lexington" },
    { state: "Kentucky", city: "Louisville" },
    { state: "Kentucky", city: "Owensboro" },
    { state: "Kentucky", city: "Richmond" },
  ],
  "Louisiana": [
    { state: "Louisiana", city: "Alexandria" },
    { state: "Louisiana", city: "Baton Rouge" },
    { state: "Louisiana", city: "Bossier City" },
    { state: "Louisiana", city: "Houma" },
    { state: "Louisiana", city: "Kenner" },
    { state: "Louisiana", city: "Lafayette" },
    { state: "Louisiana", city: "Lake Charles" },
    { state: "Louisiana", city: "Metairie" },
    { state: "Louisiana", city: "Monroe" },
    { state: "Louisiana", city: "New Orleans" },
    { state: "Louisiana", city: "Shreveport" },
  ],
  "Maine": [
    { state: "Maine", city: "Augusta" },
    { state: "Maine", city: "Bangor" },
    { state: "Maine", city: "Biddeford" },
    { state: "Maine", city: "Lewiston" },
    { state: "Maine", city: "Portland" },
    { state: "Maine", city: "South Portland" },
  ],
  "Maryland": [
    { state: "Maryland", city: "Annapolis" },
    { state: "Maryland", city: "Baltimore" },
    { state: "Maryland", city: "Bowie" },
    { state: "Maryland", city: "Columbia" },
    { state: "Maryland", city: "Frederick" },
    { state: "Maryland", city: "Gaithersburg" },
    { state: "Maryland", city: "Germantown" },
    { state: "Maryland", city: "Hagerstown" },
    { state: "Maryland", city: "Rockville" },
    { state: "Maryland", city: "Silver Spring" },
    { state: "Maryland", city: "Waldorf" },
  ],
  "Massachusetts": [
    { state: "Massachusetts", city: "Boston" },
    { state: "Massachusetts", city: "Brockton" },
    { state: "Massachusetts", city: "Cambridge" },
    { state: "Massachusetts", city: "Fall River" },
    { state: "Massachusetts", city: "Framingham" },
    { state: "Massachusetts", city: "Lawrence" },
    { state: "Massachusetts", city: "Lowell" },
    { state: "Massachusetts", city: "Lynn" },
    { state: "Massachusetts", city: "New Bedford" },
    { state: "Massachusetts", city: "Newton" },
    { state: "Massachusetts", city: "Quincy" },
    { state: "Massachusetts", city: "Somerville" },
    { state: "Massachusetts", city: "Springfield" },
    { state: "Massachusetts", city: "Waltham" },
    { state: "Massachusetts", city: "Worcester" },
  ],
  "Michigan": [
    { state: "Michigan", city: "Ann Arbor" },
    { state: "Michigan", city: "Dearborn" },
    { state: "Michigan", city: "Detroit" },
    { state: "Michigan", city: "Farmington Hills" },
    { state: "Michigan", city: "Flint" },
    { state: "Michigan", city: "Grand Rapids" },
    { state: "Michigan", city: "Kalamazoo" },
    { state: "Michigan", city: "Lansing" },
    { state: "Michigan", city: "Livonia" },
    { state: "Michigan", city: "Novi" },
    { state: "Michigan", city: "Rochester Hills" },
    { state: "Michigan", city: "Southfield" },
    { state: "Michigan", city: "Sterling Heights" },
    { state: "Michigan", city: "Troy" },
    { state: "Michigan", city: "Warren" },
    { state: "Michigan", city: "Westland" },
    { state: "Michigan", city: "Wyoming" },
  ],
  "Minnesota": [
    { state: "Minnesota", city: "Bloomington" },
    { state: "Minnesota", city: "Brooklyn Park" },
    { state: "Minnesota", city: "Burnsville" },
    { state: "Minnesota", city: "Coon Rapids" },
    { state: "Minnesota", city: "Duluth" },
    { state: "Minnesota", city: "Eagan" },
    { state: "Minnesota", city: "Eden Prairie" },
    { state: "Minnesota", city: "Edina" },
    { state: "Minnesota", city: "Lakeville" },
    { state: "Minnesota", city: "Maple Grove" },
    { state: "Minnesota", city: "Minneapolis" },
    { state: "Minnesota", city: "Minnetonka" },
    { state: "Minnesota", city: "Plymouth" },
    { state: "Minnesota", city: "Rochester" },
    { state: "Minnesota", city: "Saint Cloud" },
    { state: "Minnesota", city: "Saint Paul" },
    { state: "Minnesota", city: "Woodbury" },
  ],
  "Mississippi": [
    { state: "Mississippi", city: "Biloxi" },
    { state: "Mississippi", city: "Gulfport" },
    { state: "Mississippi", city: "Hattiesburg" },
    { state: "Mississippi", city: "Jackson" },
    { state: "Mississippi", city: "Meridian" },
    { state: "Mississippi", city: "Southaven" },
  ],
  "Missouri": [
    { state: "Missouri", city: "Blue Springs" },
    { state: "Missouri", city: "Cape Girardeau" },
    { state: "Missouri", city: "Chesterfield" },
    { state: "Missouri", city: "Columbia" },
    { state: "Missouri", city: "Florissant" },
    { state: "Missouri", city: "Independence" },
    { state: "Missouri", city: "Jefferson City" },
    { state: "Missouri", city: "Joplin" },
    { state: "Missouri", city: "Kansas City" },
    { state: "Missouri", city: "Lee's Summit" },
    { state: "Missouri", city: "O'Fallon" },
    { state: "Missouri", city: "Saint Charles" },
    { state: "Missouri", city: "Saint Joseph" },
    { state: "Missouri", city: "Saint Louis" },
    { state: "Missouri", city: "Saint Peters" },
    { state: "Missouri", city: "Springfield" },
  ],
  "Montana": [
    { state: "Montana", city: "Billings" },
    { state: "Montana", city: "Bozeman" },
    { state: "Montana", city: "Butte" },
    { state: "Montana", city: "Great Falls" },
    { state: "Montana", city: "Helena" },
    { state: "Montana", city: "Kalispell" },
    { state: "Montana", city: "Missoula" },
  ],
  "Nebraska": [
    { state: "Nebraska", city: "Bellevue" },
    { state: "Nebraska", city: "Grand Island" },
    { state: "Nebraska", city: "Kearney" },
    { state: "Nebraska", city: "Lincoln" },
    { state: "Nebraska", city: "Omaha" },
  ],
  "Nevada": [
    { state: "Nevada", city: "Carson City" },
    { state: "Nevada", city: "Enterprise" },
    { state: "Nevada", city: "Henderson" },
    { state: "Nevada", city: "Las Vegas" },
    { state: "Nevada", city: "North Las Vegas" },
    { state: "Nevada", city: "Paradise" },
    { state: "Nevada", city: "Reno" },
    { state: "Nevada", city: "Sparks" },
    { state: "Nevada", city: "Spring Valley" },
    { state: "Nevada", city: "Sunrise Manor" },
  ],
  "New Hampshire": [
    { state: "New Hampshire", city: "Concord" },
    { state: "New Hampshire", city: "Derry" },
    { state: "New Hampshire", city: "Dover" },
    { state: "New Hampshire", city: "Manchester" },
    { state: "New Hampshire", city: "Nashua" },
    { state: "New Hampshire", city: "Rochester" },
  ],
  "New Jersey": [
    { state: "New Jersey", city: "Atlantic City" },
    { state: "New Jersey", city: "Bayonne" },
    { state: "New Jersey", city: "Camden" },
    { state: "New Jersey", city: "Cherry Hill" },
    { state: "New Jersey", city: "Clifton" },
    { state: "New Jersey", city: "East Orange" },
    { state: "New Jersey", city: "Edison" },
    { state: "New Jersey", city: "Elizabeth" },
    { state: "New Jersey", city: "Hoboken" },
    { state: "New Jersey", city: "Jersey City" },
    { state: "New Jersey", city: "Lakewood" },
    { state: "New Jersey", city: "New Brunswick" },
    { state: "New Jersey", city: "Newark" },
    { state: "New Jersey", city: "Passaic" },
    { state: "New Jersey", city: "Paterson" },
    { state: "New Jersey", city: "Perth Amboy" },
    { state: "New Jersey", city: "Plainfield" },
    { state: "New Jersey", city: "Princeton" },
    { state: "New Jersey", city: "Toms River" },
    { state: "New Jersey", city: "Trenton" },
    { state: "New Jersey", city: "Union City" },
    { state: "New Jersey", city: "Vineland" },
    { state: "New Jersey", city: "Wayne" },
    { state: "New Jersey", city: "West New York" },
    { state: "New Jersey", city: "Woodbridge" },
  ],
  "New Mexico": [
    { state: "New Mexico", city: "Albuquerque" },
    { state: "New Mexico", city: "Clovis" },
    { state: "New Mexico", city: "Farmington" },
    { state: "New Mexico", city: "Hobbs" },
    { state: "New Mexico", city: "Las Cruces" },
    { state: "New Mexico", city: "Rio Rancho" },
    { state: "New Mexico", city: "Roswell" },
    { state: "New Mexico", city: "Santa Fe" },
  ],
  "New York": [
    { state: "New York", city: "Albany" },
    { state: "New York", city: "Binghamton" },
    { state: "New York", city: "Bronx" },
    { state: "New York", city: "Brooklyn" },
    { state: "New York", city: "Buffalo" },
    { state: "New York", city: "Elmira" },
    { state: "New York", city: "Hempstead" },
    { state: "New York", city: "Ithaca" },
    { state: "New York", city: "Jamestown" },
    { state: "New York", city: "Kingston" },
    { state: "New York", city: "Manhattan" },
    { state: "New York", city: "Mount Vernon" },
    { state: "New York", city: "New Rochelle" },
    { state: "New York", city: "New York City" },
    { state: "New York", city: "Niagara Falls" },
    { state: "New York", city: "Poughkeepsie" },
    { state: "New York", city: "Queens" },
    { state: "New York", city: "Rochester" },
    { state: "New York", city: "Schenectady" },
    { state: "New York", city: "Staten Island" },
    { state: "New York", city: "Syracuse" },
    { state: "New York", city: "Troy" },
    { state: "New York", city: "Utica" },
    { state: "New York", city: "White Plains" },
    { state: "New York", city: "Yonkers" },
  ],
  "North Carolina": [
    { state: "North Carolina", city: "Asheville" },
    { state: "North Carolina", city: "Burlington" },
    { state: "North Carolina", city: "Cary" },
    { state: "North Carolina", city: "Chapel Hill" },
    { state: "North Carolina", city: "Charlotte" },
    { state: "North Carolina", city: "Concord" },
    { state: "North Carolina", city: "Durham" },
    { state: "North Carolina", city: "Fayetteville" },
    { state: "North Carolina", city: "Gastonia" },
    { state: "North Carolina", city: "Greensboro" },
    { state: "North Carolina", city: "Greenville" },
    { state: "North Carolina", city: "High Point" },
    { state: "North Carolina", city: "Jacksonville" },
    { state: "North Carolina", city: "Kannapolis" },
    { state: "North Carolina", city: "Raleigh" },
    { state: "North Carolina", city: "Rocky Mount" },
    { state: "North Carolina", city: "Wilmington" },
    { state: "North Carolina", city: "Wilson" },
    { state: "North Carolina", city: "Winston-Salem" },
  ],
  "North Dakota": [
    { state: "North Dakota", city: "Bismarck" },
    { state: "North Dakota", city: "Fargo" },
    { state: "North Dakota", city: "Grand Forks" },
    { state: "North Dakota", city: "Minot" },
    { state: "North Dakota", city: "West Fargo" },
  ],
  "Ohio": [
    { state: "Ohio", city: "Akron" },
    { state: "Ohio", city: "Canton" },
    { state: "Ohio", city: "Cincinnati" },
    { state: "Ohio", city: "Cleveland" },
    { state: "Ohio", city: "Columbus" },
    { state: "Ohio", city: "Dayton" },
    { state: "Ohio", city: "Elyria" },
    { state: "Ohio", city: "Hamilton" },
    { state: "Ohio", city: "Kettering" },
    { state: "Ohio", city: "Lakewood" },
    { state: "Ohio", city: "Lorain" },
    { state: "Ohio", city: "Mansfield" },
    { state: "Ohio", city: "Mentor" },
    { state: "Ohio", city: "Middletown" },
    { state: "Ohio", city: "Parma" },
    { state: "Ohio", city: "Springfield" },
    { state: "Ohio", city: "Strongsville" },
    { state: "Ohio", city: "Toledo" },
    { state: "Ohio", city: "Warren" },
    { state: "Ohio", city: "Youngstown" },
  ],
  "Oklahoma": [
    { state: "Oklahoma", city: "Broken Arrow" },
    { state: "Oklahoma", city: "Edmond" },
    { state: "Oklahoma", city: "Enid" },
    { state: "Oklahoma", city: "Lawton" },
    { state: "Oklahoma", city: "Midwest City" },
    { state: "Oklahoma", city: "Moore" },
    { state: "Oklahoma", city: "Muskogee" },
    { state: "Oklahoma", city: "Norman" },
    { state: "Oklahoma", city: "Oklahoma City" },
    { state: "Oklahoma", city: "Stillwater" },
    { state: "Oklahoma", city: "Tulsa" },
  ],
  "Oregon": [
    { state: "Oregon", city: "Albany" },
    { state: "Oregon", city: "Beaverton" },
    { state: "Oregon", city: "Bend" },
    { state: "Oregon", city: "Corvallis" },
    { state: "Oregon", city: "Eugene" },
    { state: "Oregon", city: "Gresham" },
    { state: "Oregon", city: "Hillsboro" },
    { state: "Oregon", city: "Keizer" },
    { state: "Oregon", city: "Medford" },
    { state: "Oregon", city: "Portland" },
    { state: "Oregon", city: "Salem" },
    { state: "Oregon", city: "Springfield" },
    { state: "Oregon", city: "Tigard" },
  ],
  "Pennsylvania": [
    { state: "Pennsylvania", city: "Allentown" },
    { state: "Pennsylvania", city: "Altoona" },
    { state: "Pennsylvania", city: "Bethlehem" },
    { state: "Pennsylvania", city: "Chester" },
    { state: "Pennsylvania", city: "Easton" },
    { state: "Pennsylvania", city: "Erie" },
    { state: "Pennsylvania", city: "Harrisburg" },
    { state: "Pennsylvania", city: "Lancaster" },
    { state: "Pennsylvania", city: "Levittown" },
    { state: "Pennsylvania", city: "Philadelphia" },
    { state: "Pennsylvania", city: "Pittsburgh" },
    { state: "Pennsylvania", city: "Reading" },
    { state: "Pennsylvania", city: "Scranton" },
    { state: "Pennsylvania", city: "State College" },
    { state: "Pennsylvania", city: "Wilkes-Barre" },
    { state: "Pennsylvania", city: "York" },
  ],
  "Rhode Island": [
    { state: "Rhode Island", city: "Cranston" },
    { state: "Rhode Island", city: "East Providence" },
    { state: "Rhode Island", city: "Newport" },
    { state: "Rhode Island", city: "Pawtucket" },
    { state: "Rhode Island", city: "Providence" },
    { state: "Rhode Island", city: "Warwick" },
    { state: "Rhode Island", city: "Woonsocket" },
  ],
  "South Carolina": [
    { state: "South Carolina", city: "Aiken" },
    { state: "South Carolina", city: "Anderson" },
    { state: "South Carolina", city: "Charleston" },
    { state: "South Carolina", city: "Columbia" },
    { state: "South Carolina", city: "Florence" },
    { state: "South Carolina", city: "Goose Creek" },
    { state: "South Carolina", city: "Greenville" },
    { state: "South Carolina", city: "Hilton Head Island" },
    { state: "South Carolina", city: "Mount Pleasant" },
    { state: "South Carolina", city: "Myrtle Beach" },
    { state: "South Carolina", city: "North Charleston" },
    { state: "South Carolina", city: "Rock Hill" },
    { state: "South Carolina", city: "Spartanburg" },
    { state: "South Carolina", city: "Summerville" },
    { state: "South Carolina", city: "Sumter" },
  ],
  "South Dakota": [
    { state: "South Dakota", city: "Aberdeen" },
    { state: "South Dakota", city: "Brookings" },
    { state: "South Dakota", city: "Pierre" },
    { state: "South Dakota", city: "Rapid City" },
    { state: "South Dakota", city: "Sioux Falls" },
    { state: "South Dakota", city: "Watertown" },
  ],
  "Tennessee": [
    { state: "Tennessee", city: "Bartlett" },
    { state: "Tennessee", city: "Brentwood" },
    { state: "Tennessee", city: "Chattanooga" },
    { state: "Tennessee", city: "Clarksville" },
    { state: "Tennessee", city: "Cleveland" },
    { state: "Tennessee", city: "Collierville" },
    { state: "Tennessee", city: "Franklin" },
    { state: "Tennessee", city: "Germantown" },
    { state: "Tennessee", city: "Hendersonville" },
    { state: "Tennessee", city: "Jackson" },
    { state: "Tennessee", city: "Johnson City" },
    { state: "Tennessee", city: "Kingsport" },
    { state: "Tennessee", city: "Knoxville" },
    { state: "Tennessee", city: "Memphis" },
    { state: "Tennessee", city: "Murfreesboro" },
    { state: "Tennessee", city: "Nashville" },
    { state: "Tennessee", city: "Smyrna" },
    { state: "Tennessee", city: "Spring Hill" },
  ],
  "Texas": [
    { state: "Texas", city: "Abilene" },
    { state: "Texas", city: "Amarillo" },
    { state: "Texas", city: "Arlington" },
    { state: "Texas", city: "Austin" },
    { state: "Texas", city: "Beaumont" },
    { state: "Texas", city: "Brownsville" },
    { state: "Texas", city: "Bryan" },
    { state: "Texas", city: "Carrollton" },
    { state: "Texas", city: "College Station" },
    { state: "Texas", city: "Corpus Christi" },
    { state: "Texas", city: "Dallas" },
    { state: "Texas", city: "Denton" },
    { state: "Texas", city: "Edinburg" },
    { state: "Texas", city: "El Paso" },
    { state: "Texas", city: "Euless" },
    { state: "Texas", city: "Fort Worth" },
    { state: "Texas", city: "Frisco" },
    { state: "Texas", city: "Galveston" },
    { state: "Texas", city: "Garland" },
    { state: "Texas", city: "Grand Prairie" },
    { state: "Texas", city: "Grapevine" },
    { state: "Texas", city: "Houston" },
    { state: "Texas", city: "Irving" },
    { state: "Texas", city: "Killeen" },
    { state: "Texas", city: "Laredo" },
    { state: "Texas", city: "League City" },
    { state: "Texas", city: "Lewisville" },
    { state: "Texas", city: "Longview" },
    { state: "Texas", city: "Lubbock" },
    { state: "Texas", city: "McAllen" },
    { state: "Texas", city: "McKinney" },
    { state: "Texas", city: "Mesquite" },
    { state: "Texas", city: "Midland" },
    { state: "Texas", city: "Mission" },
    { state: "Texas", city: "New Braunfels" },
    { state: "Texas", city: "Odessa" },
    { state: "Texas", city: "Pasadena" },
    { state: "Texas", city: "Pearland" },
    { state: "Texas", city: "Pharr" },
    { state: "Texas", city: "Plano" },
    { state: "Texas", city: "Port Arthur" },
    { state: "Texas", city: "Richardson" },
    { state: "Texas", city: "Round Rock" },
    { state: "Texas", city: "San Angelo" },
    { state: "Texas", city: "San Antonio" },
    { state: "Texas", city: "Sugar Land" },
    { state: "Texas", city: "Temple" },
    { state: "Texas", city: "Texarkana" },
    { state: "Texas", city: "The Woodlands" },
    { state: "Texas", city: "Tyler" },
    { state: "Texas", city: "Victoria" },
    { state: "Texas", city: "Waco" },
    { state: "Texas", city: "Wichita Falls" },
  ],
  "Utah": [
    { state: "Utah", city: "Bountiful" },
    { state: "Utah", city: "Draper" },
    { state: "Utah", city: "Layton" },
    { state: "Utah", city: "Lehi" },
    { state: "Utah", city: "Logan" },
    { state: "Utah", city: "Millcreek" },
    { state: "Utah", city: "Murray" },
    { state: "Utah", city: "Ogden" },
    { state: "Utah", city: "Orem" },
    { state: "Utah", city: "Provo" },
    { state: "Utah", city: "Riverton" },
    { state: "Utah", city: "Saint George" },
    { state: "Utah", city: "Salt Lake City" },
    { state: "Utah", city: "Sandy" },
    { state: "Utah", city: "South Jordan" },
    { state: "Utah", city: "Spanish Fork" },
    { state: "Utah", city: "Springville" },
    { state: "Utah", city: "Taylorsville" },
    { state: "Utah", city: "Tooele" },
    { state: "Utah", city: "West Jordan" },
    { state: "Utah", city: "West Valley City" },
  ],
  "Vermont": [
    { state: "Vermont", city: "Barre" },
    { state: "Vermont", city: "Bennington" },
    { state: "Vermont", city: "Brattleboro" },
    { state: "Vermont", city: "Burlington" },
    { state: "Vermont", city: "Colchester" },
    { state: "Vermont", city: "Essex" },
    { state: "Vermont", city: "Montpelier" },
    { state: "Vermont", city: "Rutland" },
    { state: "Vermont", city: "South Burlington" },
  ],
  "Virginia": [
    { state: "Virginia", city: "Alexandria" },
    { state: "Virginia", city: "Arlington" },
    { state: "Virginia", city: "Blacksburg" },
    { state: "Virginia", city: "Charlottesville" },
    { state: "Virginia", city: "Chesapeake" },
    { state: "Virginia", city: "Danville" },
    { state: "Virginia", city: "Fairfax" },
    { state: "Virginia", city: "Fredericksburg" },
    { state: "Virginia", city: "Hampton" },
    { state: "Virginia", city: "Harrisonburg" },
    { state: "Virginia", city: "Leesburg" },
    { state: "Virginia", city: "Lynchburg" },
    { state: "Virginia", city: "Manassas" },
    { state: "Virginia", city: "Newport News" },
    { state: "Virginia", city: "Norfolk" },
    { state: "Virginia", city: "Petersburg" },
    { state: "Virginia", city: "Portsmouth" },
    { state: "Virginia", city: "Reston" },
    { state: "Virginia", city: "Richmond" },
    { state: "Virginia", city: "Roanoke" },
    { state: "Virginia", city: "Salem" },
    { state: "Virginia", city: "Staunton" },
    { state: "Virginia", city: "Suffolk" },
    { state: "Virginia", city: "Virginia Beach" },
    { state: "Virginia", city: "Williamsburg" },
    { state: "Virginia", city: "Winchester" },
  ],
  "Washington": [
    { state: "Washington", city: "Auburn" },
    { state: "Washington", city: "Bellevue" },
    { state: "Washington", city: "Bellingham" },
    { state: "Washington", city: "Bremerton" },
    { state: "Washington", city: "Burien" },
    { state: "Washington", city: "Everett" },
    { state: "Washington", city: "Federal Way" },
    { state: "Washington", city: "Kennewick" },
    { state: "Washington", city: "Kent" },
    { state: "Washington", city: "Kirkland" },
    { state: "Washington", city: "Lakewood" },
    { state: "Washington", city: "Marysville" },
    { state: "Washington", city: "Olympia" },
    { state: "Washington", city: "Pasco" },
    { state: "Washington", city: "Pullman" },
    { state: "Washington", city: "Redmond" },
    { state: "Washington", city: "Renton" },
    { state: "Washington", city: "Richland" },
    { state: "Washington", city: "Sammamish" },
    { state: "Washington", city: "Seattle" },
    { state: "Washington", city: "Shoreline" },
    { state: "Washington", city: "Spokane" },
    { state: "Washington", city: "Spokane Valley" },
    { state: "Washington", city: "Tacoma" },
    { state: "Washington", city: "Vancouver" },
    { state: "Washington", city: "Walla Walla" },
    { state: "Washington", city: "Wenatchee" },
    { state: "Washington", city: "Yakima" },
  ],
  "West Virginia": [
    { state: "West Virginia", city: "Beckley" },
    { state: "West Virginia", city: "Charleston" },
    { state: "West Virginia", city: "Clarksburg" },
    { state: "West Virginia", city: "Fairmont" },
    { state: "West Virginia", city: "Huntington" },
    { state: "West Virginia", city: "Martinsburg" },
    { state: "West Virginia", city: "Morgantown" },
    { state: "West Virginia", city: "Parkersburg" },
    { state: "West Virginia", city: "Weirton" },
    { state: "West Virginia", city: "Wheeling" },
  ],
  "Wisconsin": [
    { state: "Wisconsin", city: "Appleton" },
    { state: "Wisconsin", city: "Beloit" },
    { state: "Wisconsin", city: "Brookfield" },
    { state: "Wisconsin", city: "Eau Claire" },
    { state: "Wisconsin", city: "Fond du Lac" },
    { state: "Wisconsin", city: "Green Bay" },
    { state: "Wisconsin", city: "Janesville" },
    { state: "Wisconsin", city: "Kenosha" },
    { state: "Wisconsin", city: "La Crosse" },
    { state: "Wisconsin", city: "Madison" },
    { state: "Wisconsin", city: "Manitowoc" },
    { state: "Wisconsin", city: "Milwaukee" },
    { state: "Wisconsin", city: "New Berlin" },
    { state: "Wisconsin", city: "Oshkosh" },
    { state: "Wisconsin", city: "Racine" },
    { state: "Wisconsin", city: "Sheboygan" },
    { state: "Wisconsin", city: "Stevens Point" },
    { state: "Wisconsin", city: "Waukesha" },
    { state: "Wisconsin", city: "Wausau" },
    { state: "Wisconsin", city: "Wauwatosa" },
    { state: "Wisconsin", city: "West Allis" },
  ],
  "Wyoming": [
    { state: "Wyoming", city: "Casper" },
    { state: "Wyoming", city: "Cheyenne" },
    { state: "Wyoming", city: "Evanston" },
    { state: "Wyoming", city: "Gillette" },
    { state: "Wyoming", city: "Green River" },
    { state: "Wyoming", city: "Laramie" },
    { state: "Wyoming", city: "Rock Springs" },
    { state: "Wyoming", city: "Sheridan" },
  ],
};


/**
 * Asynchronously retrieves a list of all US states.
 *
 * @returns A promise that resolves to an array of state names.
 */
export async function getStates(): Promise<string[]> {
  // Simulate API call
  await new Promise(resolve => setTimeout(resolve, 100));
  return [...mockStates].sort(); // Return a sorted copy
}

/**
 * Asynchronously retrieves City information for a given state.
 *
 * @param state The state for which to retrieve city data.
 * @returns A promise that resolves to an array of City objects.
 */
export async function getCitiesByState(state: string): Promise<City[]> {
  // Simulate API call
  await new Promise(resolve => setTimeout(resolve, 150));
  const cities = mockCitiesByState[state] || [];
  return [...cities].sort((a,b) => a.city.localeCompare(b.city)); // Return a sorted copy
}

// Old function, can be removed or kept for different purpose
/**
 * Asynchronously retrieves City information for a given state.
 *
 * @param state The state for which to retrieve city data.
 * @returns A promise that resolves to a City object containing state and city.
 */
export async function getCity(state: string): Promise<City[]> {
  // TODO: This function signature might need to be updated if it's fetching one city,
  // or use getCitiesByState if fetching multiple.
  // For now, returning a default based on mock data.
  await new Promise(resolve => setTimeout(resolve, 100));
  const citiesForState = mockCitiesByState[state];
  if (citiesForState && citiesForState.length > 0) {
    return [citiesForState[0]]; // Return the first city as an example
  }
  return [];
}


